[package]
name = "rustcraft"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "*"
bytemuck = "*"
cgmath = "*"
log = "*"
winit = "*"
futures = "*"
once_cell = "1.21.3"
image = "*"
anyhow = "*"
